kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  namespace: default
  name: deployment-manager
rules:
- apiGroups: ["apps"] # For 1.9 clusters.  If not using 1.9, use "extensions"
  resources: ["deployments"]
  verbs: ["get", "create", "patch", "list"]

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: deployment-manager
  namespace: default
subjects:
- kind: User
  name: "gcp-project@optimistic-yeti-363002.iam.gserviceaccount.com" # Change this to the email of the service account you created
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: deployment-manager
  apiGroup: rbac.authorization.k8s.io


---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: myapp-deployment-loadbalancer
 labels:
  app: myapp-app-loadbalancer
spec:
 replicas: 1
 selector:
  matchLabels:
   app: myapp-app-loadbalancer
 template:
  metadata: 
   labels:
    app: myapp-app-loadbalancer
  spec:
   containers:
   - name: myapp-app-loadbalancer
     image: ashutosha1/gcp-project:tagversion
     ports:
     - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: myapp-service-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: myapp-app-loadbalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
